[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run -v --chip RP2040"
# producing too much output logs
# runner = "probe-rs-cli run --chip RP2040 --protocol swd"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
